### ISSUE TITLE
Verify Course Section

### ISSUE THREAD

**Issue by Ramachandran017** [shamiitltd/edu.shamiit.org#101]
1. In this page COURSE CATEGORY dropdown is required field but there is no options to select .
2. IMAGE field is required but * marks is not showing/missing.

![Screenshot (31)](https://github.com/shamiitltd/edu.shamiit.org/assets/144923018/7e7b1bfc-d5a5-4a6f-95d7-41cdb32d2e6b)

**Comment by naresh-upadhyay** [comment]
Working fine.
