### ISSUE TITLE
verify the Account Module Bank Account Section

### ISSUE THREAD

**Issue by pramodkale123** [shamiitltd/edu.shamiit.org#112]
Account module in bank section it Accept any value thier is no any validation (e.g @$%^& A aaa)

![Image](https://github.com/shamiitltd/edu.shamiit.org/assets/142470915/6806a0f9-4087-4de2-add2-ef0fe419d681)

**Comment by naresh-upadhyay** [comment]
It's okay for now, because we are not sure about every country rules for these fields
