### ISSUE TITLE
Verify Admit Card Settings

### ISSUE THREAD

**Issue by Ramachandran017** [shamiitltd/edu.shamiit.org#124]
**In this section if user update on the layout one it successfully updated but it also might be  (along with layout one changes) reflected in the  layout two page.**

Screenshot for reference

![Screenshot (40)](https://github.com/shamiitltd/edu.shamiit.org/assets/144923018/87626089-d9e3-43e5-9119-1e4100e8e8ed)
![Screenshot (41)](https://github.com/shamiitltd/edu.shamiit.org/assets/144923018/9ff6ef6b-7e75-4e36-ad8c-9c89eb1d6c2a)

**Comment by devangirathod94** [comment]
first i checked how it works and then i changed some code for this issue.

**Comment by helwadkarshramika3** [comment]
For this issue, if user updates data from layout one but the same is reflected in layout two because of data is retrieved from database. So there is no issue.
