### ISSUE TITLE
Dashboard Search Bar

### ISSUE THREAD

**Issue by kamal551994** [shamiitltd/edu.shamiit.org#14]
Validate whether all the options are directing the user to the proper page when the user clicks those options after entering the keyword in the search menu And also check when the user enters some keywords then the result should be displayed based on the keyword entered.

**Comment by kamal551994** [comment]
When the user enters any details on the "Search Bar" that time page will delay showing the results.

**Comment by kamal551994** [comment]
When the user clicks the "UnAssign Student" it shows a "404 error".

![Image](https://github.com/shamiitltd/edu.shamiit.org/assets/131572485/3cdf9ace-310b-482b-8065-5c66b785d270)

**Comment by kamal551994** [comment]
When the user clicks the "UnAssign Student" it shows a "404 error".

![Image](https://github.com/shamiitltd/edu.shamiit.org/assets/131572485/4409a100-22a3-4c41-8b8c-9f3a35ae04f8)

**Comment by kamal551994** [comment]
When the user clicks the "Student Attendance" it shows a "404 error".
<img width="960" alt="Student_Attendance" src="https://github.com/shamiitltd/edu.shamiit.org/assets/131572485/e9271ac3-60bc-4380-95bb-f6fefd77a57b">

**Comment by kamal551994** [comment]
When the user clicks the "Student Attendance Report" it shows a "404 error".
<img width="960" alt="Student_Attendance_Report" src="https://github.com/shamiitltd/edu.shamiit.org/assets/131572485/f0df7163-a97f-4025-9a02-6d5bbe19f9b0">

**Comment by kamal551994** [comment]
When the user clicks the "Disabled Student" it shows a "404 error".
<img width="960" alt="Disabled_Student" src="https://github.com/shamiitltd/edu.shamiit.org/assets/131572485/46aae80b-cadb-4430-ac04-ce55d82bcafb">

**Comment by kamal551994** [comment]
When the user clicks "**Subject Wise Attendance Report**" that time Opens "**Student Attendance Report**".

**Comment by kamal551994** [comment]
When the user clicks the "Two Factor Setting" it shows a "**404 error**" and is restricted to the "**two_factor_auth_setting**".

<img width="960" alt="Two_Factor_Setting" src="https://github.com/shamiitltd/edu.shamiit.org/assets/131572485/78cffcf1-b23b-40ce-891b-ca3affabbe6c">

**Comment by kamal551994** [comment]
When the user clicks the "Academics" it shows a "404 error".
<img width="960" alt="Academics" src="https://github.com/shamiitltd/edu.shamiit.org/assets/131572485/e13c904e-2f05-4f46-aa79-c3a1c5b96f38">

**Comment by kamal551994** [comment]
When the user clicks the "Assign Subject" it shows a "404 error".

<img width="960" alt="Assign_Subject" src="https://github.com/shamiitltd/edu.shamiit.org/assets/131572485/3baf4978-b5e1-4d31-b59e-ec72625bb093">

**Comment by kamal551994** [comment]
When the user clicks the "Class Routine" it shows a "404 error".
<img width="960" alt="Class_Routine" src="https://github.com/shamiitltd/edu.shamiit.org/assets/131572485/5ec07712-67ed-4603-8e2d-acbfca991f1e">

**Comment by kamal551994** [comment]
When the user clicks the "Study Material" it shows a "404 error".

<img width="960" alt="Study_Material" src="https://github.com/shamiitltd/edu.shamiit.org/assets/131572485/500a274c-4977-40a3-8f35-2fcd80fd77ff">

**Comment by kamal551994** [comment]
The search bar name shows "Assignment" after that when the user clicks the "Assignment" options but when opening that time shows "Assignment List".

**Comment by kamal551994** [comment]
The search bar name shows "Syllabus" after that when the user clicks the "Assignment" options but when opening that time shows "Syllabus List".

**Comment by kamal551994** [comment]
When the user clicks the "lesson plan" it shows a "404 error".

<img width="960" alt="Lesson_Plan" src="https://github.com/shamiitltd/edu.shamiit.org/assets/131572485/bea13a0d-43ab-4a9f-b260-5581135c11c5">

**Comment by kamal551994** [comment]
The search bar section shows 2 Time Show Lesson Plan Options Also When the user clicks "lesson-plan" that time opens "lesson.lesson-planner" & shows "404 error".

<img width="1252" alt="Lesson_Plan2" src="https://github.com/shamiitltd/edu.shamiit.org/assets/131572485/b0ef45fe-73b7-4096-9e53-44413599090c">
<img width="960" alt="Lesson_Lesson_Planner" src="https://github.com/shamiitltd/edu.shamiit.org/assets/131572485/8a3d00aa-2f3d-45e0-af82-c3ff69188ae7">

**Comment by kamal551994** [comment]
When the user clicks the "lessonPlan-setting" it shows a "404 error".
<img width="960" alt="Lesson_Plan_Setting" src="https://github.com/shamiitltd/edu.shamiit.org/assets/131572485/b0ee5ae7-77e4-4a04-bafd-af4665fa54de">

**Comment by kamal551994** [comment]
When the user clicks the "bank-payment" it shows a "404 error".
<img width="960" alt="Bank_Payment" src="https://github.com/shamiitltd/edu.shamiit.org/assets/131572485/42e650d2-6038-43a3-a974-7ba0706b2cf9">

**Comment by kamal551994** [comment]
When the user clicks the "payment Report" it shows a "404 error".
<img width="960" alt="Payment_Report" src="https://github.com/shamiitltd/edu.shamiit.org/assets/131572485/d0fea6c8-6fa2-45c0-858a-302f968b8575">

**Comment by kamal551994** [comment]
When the user clicks the "Search Fees Payment" it shows a "404 error".
<img width="960" alt="Search_Fees_Payment" src="https://github.com/shamiitltd/edu.shamiit.org/assets/131572485/8a99c6dd-3241-4d25-a164-ae677a24fb5b">

**Comment by kamal551994** [comment]
When the user clicks the "Search Fees Due" it shows a "404 error".
<img width="960" alt="Search_Fees_Due" src="https://github.com/shamiitltd/edu.shamiit.org/assets/131572485/abab486b-a843-4929-977d-f66b09410227">

**Comment by kamal551994** [comment]
When the user clicks the "Fess Carry Forward" it shows a "404 error".
<img width="960" alt="Fess_Carry_Forward" src="https://github.com/shamiitltd/edu.shamiit.org/assets/131572485/e4cce3c6-aa90-407b-96a1-17a494a72afa">

**Comment by kamal551994** [comment]
When the user clicks the "Wallet" it shows a "404 error".
<img width="960" alt="Wallet" src="https://github.com/shamiitltd/edu.shamiit.org/assets/131572485/15d0c3f2-0523-4926-81f9-dfe721f00646">

**Comment by kamal551994** [comment]
When the user clicks the "Approve Diposite" it shows a "404 error".
<img width="960" alt="Approve Diposite" src="https://github.com/shamiitltd/edu.shamiit.org/assets/131572485/54e382f8-5981-443e-9fc7-8ebd1212be37">

**Comment by kamal551994** [comment]
When the user clicks the "Wallet Transaction" it shows a "404 error".
<img width="960" alt="Wallet_Transaction" src="https://github.com/shamiitltd/edu.shamiit.org/assets/131572485/67fe069f-0e73-4a7c-9ab8-787df4aa8b85">

**Comment by kamal551994** [comment]
When the user clicks the "Wallet refund Request" it shows a "404 error".
<img width="960" alt="Wallet refund Request" src="https://github.com/shamiitltd/edu.shamiit.org/assets/131572485/803219ca-5a36-4725-95ec-02404f94b431">

**Comment by kamal551994** [comment]
When the user clicks the "Wallet Report" it shows a "404 error".
<img width="960" alt="Wallet Report" src="https://github.com/shamiitltd/edu.shamiit.org/assets/131572485/d29017d1-0dd5-434e-835b-4451e1e35807">

**Comment by kamal551994** [comment]
When The User clicks any option from the Search bar that shows "404 error".

**Comment by naresh-upadhyay** [comment]
Issue fixed please re-test. On test env @kamal551994

**Comment by kamal551994** [comment]
Sir currently i am still able find 404 Error in few options on Dashboard search bar.
