### ISSUE TITLE
To check that academics module class room section

### ISSUE THREAD

**Issue by Ramachandran017** [shamiitltd/edu.shamiit.org#181]
- > -Here user enter invalid data in the "Capacity" text field it accepts. (example is given below)
- >  later it shows default value "0" 
- >  Problem is it doesn't indicate "error message".
- >  

 Screen shots for reference!

![Image](https://github.com/shamiitltd/edu.shamiit.org/assets/144923018/1e4e4951-a100-49fe-a25f-ea7fdfb7edc8)
![Image](https://github.com/shamiitltd/edu.shamiit.org/assets/144923018/565dea69-2d23-4eff-abce-13b1f442e78f)
![Image](https://github.com/shamiitltd/edu.shamiit.org/assets/144923018/eb42da0a-c88b-4ef7-ba9d-381c940cf24b)

**Comment by Ramachandran017** [comment]
One more thing I want to know the functionality of "Room No" text field because it accepts only special chars and alphanumeric. @vinay-upadhyay

**Comment by naresh-upadhyay** [comment]
Low priority issue.
