### ISSUE TITLE
User can't add new Staff

### ISSUE THREAD

**Issue by kamal551994** [shamiitltd/edu.shamiit.org#187]
Add Staff issue.

![Image](https://github.com/shamiitltd/edu.shamiit.org/assets/131572485/04e063d4-c3ba-4754-b415-a03d50097000)

**Comment by kamal551994** [comment]
When user try to "ADD STAFF" that time user can't add new staff. That time System will send massage "Failed - Operation Failed".

![Image](https://github.com/shamiitltd/edu.shamiit.org/assets/131572485/56888cfd-600c-42a9-b6d9-789f5860ea54)

**Comment by naresh-upadhyay** [comment]
@kamal551994  Try again it's working fine from our side.

**Comment by kamal551994** [comment]
Issue is close by me[Sk Kamaluddin]
