### ISSUE TITLE
Verify Fees Invoice section in Fees module

### ISSUE THREAD

**Issue by helwadkarshramika3** [shamiitltd/edu.shamiit.org#195]
After generating Fees Invoice, it's successfully storing data but data is not reflected on Fees Invoice table. Instead of that it is showing **Processing...** .

Attached screenshot for reference-

1. ![Image](https://github.com/shamiitltd/edu.shamiit.org/assets/144815633/9c160bd5-5b6f-4994-a70f-24d06700c819)

2. ![Image](https://github.com/shamiitltd/edu.shamiit.org/assets/144815633/9e907724-65d0-4f3f-b0ec-bab2e0983438)

**Comment by shamiit** [comment]
@mesnehadutta is this valid issue?

**Comment by devangirathod94** [comment]
Task completed

**Comment by kamal551994** [comment]
@pranavnavle

**Comment by pranavnavle** [comment]
Now it's working properly.[Pranav Navale]
