### ISSUE TITLE
Verify Staff Attendance Import section of HR module

### ISSUE THREAD

**Issue by helwadkarshramika3** [shamiitltd/edu.shamiit.org#198]
In Staff Attendance  Import section, when user tries to upload Excel file (xlsx, csv) but in file field is not reflecting any information about uploaded file.

Attached screenshot for reference-

1. ![Image](https://github.com/shamiitltd/edu.shamiit.org/assets/144815633/cd287f42-7215-42f0-8514-3b190a864f81)

2. ![Image](https://github.com/shamiitltd/edu.shamiit.org/assets/144815633/52bfb9e1-d10f-4265-b3ed-b29f97d3777a)

**Comment by mesnehadutta** [comment]
Solved.I put it in sit testing section

**Comment by helwadkarshramika3** [comment]
Now it's working properly.

Attached screenshot for reference-

![Image](https://github.com/shamiitltd/edu.shamiit.org/assets/144815633/4ab4bc26-38da-4bbd-83b4-88757534c5ac)
