### ISSUE TITLE
Verify Staff Attendance Report section of Staff Report

### ISSUE THREAD

**Issue by helwadkarshramika3** [shamiitltd/edu.shamiit.org#199]
In Staff Attendance Report section,  for 9th date of Monday it is showing string of numbers at the start but Present , Absent and Late at the end of string instead of Present , Absent and Late (P / A / L) for all roles whose reports are generated in October month.

Attached screenshot for reference-

![Image](https://github.com/shamiitltd/edu.shamiit.org/assets/144815633/06ab29f0-c171-497c-9a76-62b178075b47)

**Comment by mesnehadutta** [comment]
This issue is solved
