### ISSUE TITLE
Verify Leave Define section of Leave module

### ISSUE THREAD

**Issue by helwadkarshramika3** [shamiitltd/edu.shamiit.org#213]
In Leave Define List, when user tries to define leave its showing alert message as **Operation Successful** but data is not reflecting into Leave Define List table.

Attached screenshot for reference-

1. ![Image](https://github.com/shamiitltd/edu.shamiit.org/assets/144815633/415e6bda-62d5-4189-a2b7-68cb88314d76)

2. ![Image](https://github.com/shamiitltd/edu.shamiit.org/assets/144815633/5de26090-6665-4458-8db8-b423ad26b755)

**Comment by shamiit** [comment]
when data is present for users then it's working fine.
