### ISSUE TITLE
Parent profile name not showing

### ISSUE THREAD

**Issue by pranavnavle** [shamiitltd/edu.shamiit.org#269]
When login as a parent - Parent Name does not showing in dashboard.
ID - guardian_18@edu.shamiit.org
Password - 123456
Attached Screenshot for reference

![Image](https://github.com/shamiitltd/edu.shamiit.org/assets/124654793/dc02b888-fa5c-4c18-a002-dc292086e577)

**Comment by devangirathod94** [comment]
completed

**Comment by pranavnavle** [comment]
Now its working fine .
