### ISSUE TITLE
Verify Image field for Student Photo field in Student Certificate page

### ISSUE THREAD

**Issue by helwadkarshramika3** [shamiitltd/edu.shamiit.org#29]
In Add Certificate section for Student Photo field, Image field is unavailable but Image field is available for Background image.

Attached screenshot for reference-

![Image](https://github.com/shamiitltd/edu.shamiit.org/assets/144815633/1bb88767-ebbc-4e47-84ff-9a96fc72a6d0)

**Comment by naresh-upadhyay** [comment]
Student Photo is not getting upload while adding it's details, parent photo uploading and visible, guardian photo upload but not visible. SID: 33238 @helwadkarshramika3 
https://test.edu.shamiit.org/student-view/1


![Image](https://github.com/shamiitltd/edu.shamiit.org/assets/46640388/9a12d783-44ac-44ef-b1ff-d6629621ec87)



![Image](https://github.com/shamiitltd/edu.shamiit.org/assets/46640388/416865e4-9f1e-4f8e-8449-331aa2c1e38d)

**Comment by naresh-upadhyay** [comment]
"Student Photo field, Image field is unavailable" because it's only flag (That we can implement in future), we can customize certificate according to need/ School demand.
