### ISSUE TITLE
To verify that missing mandatory text field

### ISSUE THREAD

**Issue by Ramachandran017** [shamiitltd/edu.shamiit.org#31]
In this module there is no text field to enter the data  for "Section" field and it is mandatory field also so without this we can't save anything.

![Screenshot (47)](https://github.com/shamiitltd/edu.shamiit.org/assets/144923018/a8665d12-c55f-47e3-a7ae-f94913456b33)

**Comment by naresh-upadhyay** [comment]
Working fine mark close
