### ISSUE TITLE
Verify assign class teacher  section

### ISSUE THREAD

**Issue by pranavnavle** [shamiitltd/edu.shamiit.org#33]
In assign class teacher section here is not teacher field  but when we click on save class teacher button it shows teacher field is required.

![Image](https://github.com/shamiitltd/edu.shamiit.org/assets/124654793/7264af27-99c3-427a-9e79-118c2ef72aa3)

**Comment by naresh-upadhyay** [comment]
Because of no data it was showing like this, no error. @pranavnavle
