### ISSUE TITLE
Verify ID Card module in Admin Section

### ISSUE THREAD

**Issue by helwadkarshramika3** [shamiitltd/edu.shamiit.org#35]
On clicking ID Card module, user getting Error page.

Attached screenshot for reference-

![Image](https://github.com/shamiitltd/edu.shamiit.org/assets/144815633/91e26832-42e7-4eea-822c-dbef60db067a)

**Comment by naresh-upadhyay** [comment]
https://test.edu.shamiit.org/student-id-card

Not working

**Comment by naresh-upadhyay** [comment]
Now verify again @helwadkarshramika3

**Comment by helwadkarshramika3** [comment]
Now it's working properly @naresh-upadhyay. 

Attached screenshot for your reference - 

![Image](https://github.com/shamiitltd/edu.shamiit.org/assets/144815633/f5a3b23d-6a5c-40df-b84f-3159dd740f94)

**Comment by helwadkarshramika3** [comment]
Now again it's showing error page @naresh-upadhyay.

Attached screenshot for reference-

![Image](https://github.com/shamiitltd/edu.shamiit.org/assets/144815633/b81a5f27-2940-4057-8623-78cae3722510)
