### ISSUE TITLE
Verify Custom field section of Add New Staff module

### ISSUE THREAD

**Issue by helwadkarshramika3** [shamiitltd/edu.shamiit.org#37]
On Add New Staff module,
data is unavailable in Custom field section.

Attached screenshot for reference- 

![Image](https://github.com/shamiitltd/edu.shamiit.org/assets/144815633/7c17ece8-41d0-4254-a4e6-9181d5ff72f1)

**Comment by naresh-upadhyay** [comment]
IT's okay
