### ISSUE TITLE
Verify Payroll section in Human Resource module

### ISSUE THREAD

**Issue by helwadkarshramika3** [shamiitltd/edu.shamiit.org#38]
On Generate Payroll page in Staff List section, when user selects Proceed to Pay action in that Expense Head dropdown is not displaying any options. 
Also when user clicks on Save Information button it is not displaying error message below Expense Head dropdown.

Attached screenshot for reference-

![Image](https://github.com/shamiitltd/edu.shamiit.org/assets/144815633/6e206df0-f0db-4cbc-a126-97cc420f0539)

**Comment by HariomParmar2807** [comment]
we can add expense in expense section in account

**Comment by kamal551994** [comment]
Currently Issue is solve.

![Image](https://github.com/shamiitltd/edu.shamiit.org/assets/131572485/ecc5d23c-6349-4e80-9780-6a5921551b46)
