### ISSUE TITLE
Verify Staff Attendance Import module of Human Resource

### ISSUE THREAD

**Issue by helwadkarshramika3** [shamiitltd/edu.shamiit.org#58]
In Staff Attendance Import module, 

1. When user tries to upload .csv file it throws an error with message "The file must be a file of type: xlsx, csv."
2. When user tries to upload any .xlsx file other than sample file it shows alert message as "operation failed".

Attached screenshots for reference-

1. ![Image](https://github.com/shamiitltd/edu.shamiit.org/assets/144815633/b15ebdce-03f0-4552-9916-8848bb0f5f46)

2. ![Image](https://github.com/shamiitltd/edu.shamiit.org/assets/144815633/9ce99567-1006-4f27-ba49-f64aaa0aa6de)

**Comment by shamiit** [comment]
This needs to be re-tested

**Comment by helwadkarshramika3** [comment]
@shamiit  this issue is working fine for **Sample File** only but when i tries to upload any other .csv file it throws an error with message "The file must be a file of type: xlsx, csv" and also when i tries to upload any .xlsx file other than sample file it shows alert message as "operation failed".

**Comment by shamiit** [comment]
Upload sample file after adding some more records. @helwadkarshramika3

**Comment by helwadkarshramika3** [comment]
@shamiit this issue is working fine after adding some more records. Thank you sir.

Attached screenshot for reference- 

![Image](https://github.com/shamiitltd/edu.shamiit.org/assets/144815633/215ddded-78cc-42fa-9e60-3b28c4a98b27)
