### ISSUE TITLE
Verify the functionality of the Fees module's Fees Invoice section

### ISSUE THREAD

**Issue by pramodkale123** [shamiitltd/edu.shamiit.org#59]
In the Fees Module's "Fees Invoice" section, the " SECTION" Dropdown is not working

![Image](https://github.com/shamiitltd/edu.shamiit.org/assets/142470915/4ea289f5-9ba6-460a-becd-7b85207b7db5)

**Comment by naresh-upadhyay** [comment]
Working fine.
