### ISSUE TITLE
Verify Phone field on Visitor Book

### ISSUE THREAD

**Issue by helwadkarshramika3** [shamiitltd/edu.shamiit.org#6]
In Add Visitor section,
**Phone** field accepting numbers without any limit.

**Comment by mohityadav8600** [comment]
which type of verify otp or simple count a mobile number?

**Comment by helwadkarshramika3** [comment]
@mohityadav8600 simple count of mobile number. Please refer below screenshot for detail  - 

![Image](https://github.com/shamiitltd/edu.shamiit.org/assets/144815633/68938762-ce0b-4966-a6e6-6ef72008066c)

**Comment by helwadkarshramika3** [comment]
It's acceptable for phone field to accept any numbers without limit. So it's working properly.

Attached screenshot for reference-

![Image](https://github.com/shamiitltd/edu.shamiit.org/assets/144815633/896ca6a5-2d52-47df-b289-5cd7e4d06ee7)
