### ISSUE TITLE
Verify Assign Permission section in Role & permission module

### ISSUE THREAD

**Issue by helwadkarshramika3** [shamiitltd/edu.shamiit.org#66]
In Assign Permission section, the modules which are having sub modules with radio button options are having incorrect alignment.

Attached screenshot for reference-

![Image](https://github.com/shamiitltd/edu.shamiit.org/assets/144815633/913f2764-0bed-4e84-bc41-27d76414e752)

**Comment by naresh-upadhyay** [comment]
Update on this story @sweetiagrahari

**Comment by sweetiagrahari** [comment]
sir  I did not able to get  error page  path in local server. here in inspect I checked.

**Comment by naresh-upadhyay** [comment]
issue fixed.
