### ISSUE TITLE
Verify functionality of DELETE button

### ISSUE THREAD

**Issue by helwadkarshramika3** [shamiitltd/edu.shamiit.org#8]
On clicking **DELETE** button of action dropdown it is redirected to error webpage and unable to delete records.

Attached screenshots for reference -

1. ![Image](https://github.com/shamiitltd/edu.shamiit.org/assets/144815633/b5258ff7-237c-4578-82cd-15303b2d1965)

2. ![Image](https://github.com/shamiitltd/edu.shamiit.org/assets/144815633/6b35d474-bb57-4f93-952b-813bcbc5c9ab)

**Comment by naresh-upadhyay** [comment]
Update on the story @mohityadav8600 ?

**Comment by mohityadav8600** [comment]
sir i change post to get method and some other change on this
