### ISSUE TITLE
Verify Add member section in library module

### ISSUE THREAD

**Issue by pranavnavle** [shamiitltd/edu.shamiit.org#92]
Verify Add member in library module ,When we add member as a admin then mobile numbers are add by default but numbers added by default is sometimes 9 digits . There should be option for edit numbers.

![Image](https://github.com/shamiitltd/edu.shamiit.org/assets/124654793/32cf89ae-db0f-4e79-87ed-8b09f53393d8)

**Comment by shamiit** [comment]
![Image](https://github.com/shamiitltd/edu.shamiit.org/assets/115389010/2c41ae62-a22b-4ee1-8bb8-64dad69d5605)

No problem at all
